import type { DirectoryItem } from "../types";

import doctorImg from "../../../assets/img/main/doctor.png";
import nurseImg from "../../../assets/img/main/nurse.png";
import pharmacyImg from "../../../assets/img/main/pharmacy.png";
import clinicImg from "../../../assets/img/main/clinic.png";

export const doctorSpecialties = [
  "All Specialties",
  "Cardiologist",
  "Neurologist",
  "Pediatrician",
  "Orthopedic Surgeon",
  "Dermatologist",
  "General Practitioner",
  "Ophthalmologist",
  "Psychiatrist",
] as const;

export type DoctorSpecialty = (typeof doctorSpecialties)[number];

export const directoryItems: DirectoryItem[] = [
  {
    id: "dir-1",
    name: "Dr. Sarah Mitchell",
    role: "Doctor",
    specialty: "Cardiologist",
    location: "Kuala Lumpur",
    rating: 4.9,
    availability: "Available Today",
    image: doctorImg,
    badge: "Top Rated",
  },
  {
    id: "dir-2",
    name: "Dr. Ahmad Ridho",
    role: "Doctor",
    specialty: "Neurologist",
    location: "Johor Bahru",
    rating: 4.8,
    availability: "Available Tomorrow",
    image: doctorImg,
  },
  {
    id: "dir-3",
    name: "Dr. Emily Chen",
    role: "Doctor",
    specialty: "Pediatrician",
    location: "Penang",
    rating: 5.0,
    availability: "Available Today",
    image: doctorImg,
    badge: "Top Rated",
  },
  {
    id: "dir-4",
    name: "SRN Mary",
    role: "Nurse",
    specialty: "Professional Home Nursing Care",
    location: "Johor Bahru",
    rating: 4.8,
    availability: "Available Now",
    image: nurseImg,
    badge: "Verified",
    slug: "srn-mary",
  },
  {
    id: "dir-5",
    name: "SRN Ahmed",
    role: "Nurse",
    specialty: "General & Specialized Nursing",
    location: "Kuala Lumpur",
    rating: 4.7,
    availability: "Available Today",
    image: nurseImg,
    slug: "srn-ahmed",
  },
  {
    id: "dir-6",
    name: "SRN Sarah",
    role: "Nurse",
    specialty: "Pediatric & Family Nursing",
    location: "Petaling Jaya",
    rating: 4.9,
    availability: "Available Tomorrow",
    image: nurseImg,
    badge: "Verified",
    slug: "srn-sarah",
  },
  {
    id: "dir-7",
    name: "MedPlus Pharmacy",
    role: "Vendor",
    specialty: "Licensed Pharmacy",
    location: "Shah Alam",
    rating: 4.7,
    availability: "Open 24/7",
    image: pharmacyImg,
  },
  {
    id: "dir-8",
    name: "Caring Health Pharmacy",
    role: "Vendor",
    specialty: "Licensed Pharmacy",
    location: "Kuala Lumpur",
    rating: 4.6,
    availability: "Open until 10 PM",
    image: pharmacyImg,
  },
  {
    id: "dir-9",
    name: "Pristine Health Clinic",
    role: "Clinic",
    specialty: "General Practice",
    location: "Mont Kiara",
    rating: 4.9,
    availability: "Accepting Patients",
    image: clinicImg,
    badge: "Premium",
  },
  {
    id: "dir-10",
    name: "Klinik Kesihatan Jaya",
    role: "Clinic",
    specialty: "Family Clinic",
    location: "Subang Jaya",
    rating: 4.5,
    availability: "Accepting Patients",
    image: clinicImg,
  },
  {
    id: "dir-11",
    name: "Dr. Rajesh Kumar",
    role: "Doctor",
    specialty: "Orthopedic Surgeon",
    location: "Kuala Lumpur",
    rating: 4.9,
    availability: "Available This Week",
    image: doctorImg,
    badge: "Specialist",
  },
  {
    id: "dir-12",
    name: "Sunrise Specialist Clinic",
    role: "Clinic",
    specialty: "Multi-specialty Clinic",
    location: "Petaling Jaya",
    rating: 4.8,
    availability: "Accepting Patients",
    image: clinicImg,
    badge: "Premium",
  },
  {
    id: "dir-13",
    name: "Dr. Nurul Aisyah",
    role: "Doctor",
    specialty: "Dermatologist",
    location: "Bangsar",
    rating: 4.8,
    availability: "Available Today",
    image: doctorImg,
    badge: "Premium",
  },
  {
    id: "dir-14",
    name: "Dr. James Tan",
    role: "Doctor",
    specialty: "General Practitioner",
    location: "Damansara",
    rating: 4.6,
    availability: "Available Now",
    image: doctorImg,
  },
  {
    id: "dir-15",
    name: "Dr. Priya Nair",
    role: "Doctor",
    specialty: "Ophthalmologist",
    location: "Kuala Lumpur",
    rating: 4.9,
    availability: "Available Tomorrow",
    image: doctorImg,
    badge: "Specialist",
  },
  {
    id: "dir-16",
    name: "Dr. Lim Wei Jie",
    role: "Doctor",
    specialty: "Psychiatrist",
    location: "Petaling Jaya",
    rating: 4.7,
    availability: "Available This Week",
    image: doctorImg,
  },
];
